language: c
sudo: false
cache:
  directories:
    - $HOME/.opam
addons:
  apt:
    packages:
      - libgmp-dev
      - opam
      - ghc
    sources: [avsm]

matrix:
  include:
    - os: linux
      env: COQ_VER=8.5.2

    - os: linux
      env: COQ_VER=8.6.1

    - os: linux
      env: COQ_VER=8.7.2

    - os: linux
      env: COQ_VER=8.8.0


  allow_failures:
    - env: COQ_VER=8.8.0
    - env: COQ_VER=8.7.2


notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
  - ./scripts/opam-build.sh init
script:
  - ./scripts/opam-build.sh build
  - ./scripts/opam-build.sh html
  - ./scripts/opam-build.sh install
  - eval `opam config env --root=coq-"$COQ_VER"`
  - make -C crypto-lib libverse
  - make -C crypto-lib/libverse libverse.a
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - develop
