language: c
sudo: false
cache:
  directories:
    - $HOME/.opam
addons:
  apt:
    packages:
      - libgmp-dev
      - opam
      - ghc
    sources: [avsm]
env:
  global:
    - OCAML_VER=4.05.0
  matrix:
    - COQ_VER=8.5.2
    - COQ_VER=8.6.1
    - COQ_VER=8.7.2
    - COQ_VER=8.8.0

  allow_failures:
    - env: COQ_VER=8.8.0
    - env: COQ_VER=8.7.2


notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
  - opam init -y
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam update
  - opam switch install 4.05.0
  - opam switch set 4.05.0
  - opam install coq."$COQ_VER"
  - opam pin add coq "$COQ_VER"
  - opam install coq-color
script:
  - eval $(opam config env)
  - make build
  - make html
  - make -C crypto-lib libverse
  - make -C crypto-lib/libverse libverse.a
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - develop
