language: c
sudo: false
cache:
  directories:
    - $HOME/.opam
addons:
  apt:
    packages:
      - libgmp-dev
      - opam
      - ghc
    sources: [avsm]
matrix:
  include:
    - env: COQ_VER=8.5.2 OCAML_VER=4.05.0
    - env: COQ_VER=8.6.1 OCAML_VER=4.05.0
    - env: COQ_VER=8.7.2 OCAML_VER=4.05.0
    - env: COQ_VER=8.8.0 OCAML_VER=4.05.0
  allow_failures:
    - env: COQ_VER=8.8.0 OCAML_VER=4.05.0
    - env: COQ_VER=8.7.2 OCAML_VER=4.05.0


notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
  - opam init -y
  - (opam repo list | grep coq-released) || opam repo add coq-released https://coq.inria.fr/opam/released
  - opam update
  - opam switch set 4.05.0
  - opam install coq."$COQ_VER" -y --verbose
  - opam pin add coq "$COQ_VER"
  - opam install coq-color -y --verbose
script:
  - eval $(opam config env)
  - ./configure.sh
  - make
  - make html
  - make -C crypto-lib libverse
  - make -C crypto-lib/libverse libverse.a
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - develop
