name: Building and testing
on: [push, pull_request]
jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq: [ latest, '8.11', '8.10', '8.9', '8.8', '8.7']
    container: coqorg/coq:${{ matrix.coq }}
    steps:
      - name: Setup
        run: |
          sudo apt-get update -y
      - name: Information
        run: |
          echo $PATH

      - name: Get the Repository
        uses: actions/checkout@v2
