name: CI
on:
  push:
  pull_request:
  schedule:
    # Daily build.
    - cron: '0 8 * * *'

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq: [ '8.12.2', '8.11.2', '8.10.2' ]
    env:
      COQVER:  ${{ matrix.coq }}
    steps:
      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install ocaml m4 -y
          sudo add-apt-repository ppa:avsm/ppa -y
          sudo apt-get update -y
          sudo apt-get install opam indent texlive texlive-latex-extra -y

      - name: Opam Setup
        run: |
          opam --version
          opam init -y

      - name: Coq Installation
        run: |
          opam pin add coq "$COQVER" -y
      - name: Dune build
        run: |
          opam install dune -y
          eval $(opam config env)
          dune build
      - name: Build
        run: |
          eval $(opam config env)
          coqtop --version
          make all
      - name: Test
        run: |
          eval $(opam config env)
          coqtop --version
          make test
      - name: Documentation
        run: |
          eval $(opam config env)
          coqtop --version
          make html
          make all.pdf
