name: CI
on:
  push:
  pull_request:
  schedule:
    # Daily build.
    - cron: '0 8 * * *'

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq: [ '8.12.2', '8.11.2', '8.10.2' ]
    env:
      COQVER:  ${{ matrix.coq }}
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_script: |
            {{before_script}}
            {{script}}

          before_script: |
            startGroup "Getting the pre-req"
              sudo apt-get update -y
              sudo apt-get install m4 indent texlive texlive-latex-extra -y
            endGroup
          script: |
            startGroup "making library and docs"
               make
               make -C test
               make html
               make all.pdf
            endGroup
